version: '3.7'

services:
  learnhear:
    volumes:
      - learnhearCore:/learnhearCore
    env_file:
      - envfile.env
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: learnhearpostgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: learhear4$
    ports:
      - "5432:5432"

volumes:
  learnhearCore:
