databases:
  - name: eyelearn
    plan: free
    databaseName: eyelearn
    user: eyelearn_user

services:
  - type: web
    plan: free
    name: eyelearn
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learnhearCore.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eyelearn
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4