# Generated by Django 4.2.3 on 2023-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_alter_practicetimestamp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='choices',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
