# Generated by Django 4.2.3 on 2023-12-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_practice_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=100, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_question_choices', to='practices.practice')),
            ],
        ),
    ]
