# Generated by Django 4.2.3 on 2023-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('practice_audio_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
