# Generated by Django 4.2.3 on 2023-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='practice_audio_url',
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_audio',
            field=models.FileField(blank=True, null=True, upload_to='practice_audio/'),
        ),
    ]
