# Generated by Django 4.2.3 on 2023-10-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0003_practice_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DurationField()),
                ('lyrics', models.TextField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_lyrics_timestamps', to='practices.practice')),
            ],
        ),
        migrations.CreateModel(
            name='Practice_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_images', models.FileField(blank=True, null=True, upload_to='practice_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_images', to='practices.practice')),
            ],
        ),
    ]
