# Generated by Django 4.2.3 on 2023-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_practicetimestamp_practice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
