# Generated by Django 4.2.3 on 2023-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0005_practice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetimestamp',
            name='timestamp',
            field=models.CharField(max_length=8),
        ),
    ]
