# Generated by Django 4.2.3 on 2023-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='lesson',
        ),
        migrations.AddField(
            model_name='level',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, to='lessons.lesson'),
        ),
    ]
