# Generated by Django 4.2.3 on 2023-10-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_lesson_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricsTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('lyrics', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_timestamps', to='lessons.lesson')),
            ],
        ),
    ]
