# Generated by Django 4.2.3 on 2023-10-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lyricstimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricstimestamp',
            name='timestamp',
            field=models.DurationField(),
        ),
    ]
