# Generated by Django 4.2.3 on 2023-10-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lyricstimestamp_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_images', models.FileField(blank=True, null=True, upload_to='lesson_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_images', to='lessons.lesson')),
            ],
        ),
    ]
