# Generated by Django 4.2.3 on 2023-10-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lesson_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson_Images',
            new_name='Lesson_Image',
        ),
    ]
