# Generated by Django 4.2.3 on 2023-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_bridge_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
