# Generated by Django 4.2.3 on 2023-11-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_pupildata_learners_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupildata',
            name='nickname',
        ),
    ]
