# Generated by Django 4.2.3 on 2023-12-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_pupildata_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_token', models.TextField(blank=True, null=True, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
