# Generated by Django 4.2.3 on 2023-12-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pupilrecordmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilrecordmanager',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pupilrecordmanager',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_token', to='accounts.tokenmanager'),
        ),
    ]
