# Generated by Django 4.2.3 on 2023-12-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_alter_practicetimestamp_timestamp'),
        ('accounts', '0010_pupilrecordmanager_score_pupilrecordmanager_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilrecordmanager',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pupilrecordmanager',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='pupilrecordmanager',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='practices.practice'),
        ),
        migrations.AlterField(
            model_name='pupilrecordmanager',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
