# Generated by Django 4.2.3 on 2023-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_level_lesson_level_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='lesson',
        ),
        migrations.AddField(
            model_name='level',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='level_lessons', to='lessons.lesson'),
        ),
    ]
