# Generated by Django 4.2.3 on 2023-10-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_lesson_lesson_lesson_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audio/'),
        ),
    ]
