# Generated by Django 4.2.3 on 2023-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_rename_lesson_images_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricstimestamp',
            name='timestamp',
            field=models.CharField(max_length=8),
        ),
    ]
