# Generated by Django 4.2.3 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lyricstimestamp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bridge_audio',
            field=models.FileField(blank=True, null=True, upload_to='bridge_audio/'),
        ),
    ]
